### ISSUE TITLE
Melhorar a UI de Login

### ISSUE THREAD

**Issue by pedromassango** [MartinhoMCM/Saude.Healthy#1]
Trabalhar na UI de login, e deixar com uma aparência mais agradável.

**Comment by MartinhoMCM** [comment]
Ok! Vou tentar o seguir do padrão no material.io

**Comment by pedromassango** [comment]
> Ok! Vou tentar o seguir do padrão no material.io

Melhor ainda, eles têm o melhor padrão de design para seguir
